version: '3.1'
services:
  db:
    container_name: db-c
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_DB=testDB
      - POSTGRES_USER=jagath
      - POSTGRES_PASSWORD=jagath123

  adminer:
    container_name: adminer-c
    image: adminer
    restart: always
    ports:
      - 8080:8080

  my-app:
    container_name: my-app-c
    image: my-app-image
    build: .
    ports:
      - 3000:3000

volumes:
  postgres_data:

  # pgadmin:
  #   container_name: pgadmin4_container
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   ports:
  #     - "5050:5050"
  #   depends_on:
  #     - db
